import type { PerformanceDecision, PortfolioRecommendation } from "@/lib/decisions/types";
import type { BusinessGoals, IntelligenceSuiteResult, IntelligenceAnomaly } from "./types";
function pct(current:number,previous:number):number|null{if(!Number.isFinite(current)||!Number.isFinite(previous)||previous===0)return null;return((current-previous)/previous)*100;}
function guarded(d:PerformanceDecision){const m=d.currentMetrics;const direct=["LEAD_GENERATION","MESSAGES","CONVERSIONS","SALES"].includes(d.objective);const started=d.startDate?new Date(d.startDate).getTime():NaN;const learning=Number.isFinite(started)&&Math.floor((Date.now()-started)/86_400_000)<3;const lowVolume=direct?m.results<3&&m.clicks<30:m.impressions<2000;const blocked=learning||d.confidence==="low"||lowVolume;const reason=learning?"La campaña lleva menos de tres días; aún está en fase de aprendizaje.":blocked?"Volumen insuficiente para recomendar un cambio fuerte con confianza.":null;return{entityId:d.entityId,entityName:d.entityName,blocked,reason};}
export function buildIntelligenceSuite(decisions:PerformanceDecision[],goals:BusinessGoals={},portfolioRecommendations:PortfolioRecommendation[]=[]):IntelligenceSuiteResult{
 const learningGuards=decisions.map(guarded);const blocked=new Set(learningGuards.filter(g=>g.blocked).map(g=>g.entityId));
 const anomalies:IntelligenceAnomaly[]=decisions.flatMap(d=>{const comparable=d.currentResultsAvailable!==false&&d.previousResultsAvailable!==false&&(!d.resultType||d.resultType===d.previousResultType);const changes:[[string,number|null],[string,number|null],[string,number|null],[string,number|null]]=[["CTR",pct(d.currentMetrics.ctr,d.previousMetrics.ctr)],["CPC",pct(d.currentMetrics.cpc,d.previousMetrics.cpc)],["Costo por resultado",comparable?pct(d.currentMetrics.costPerResult,d.previousMetrics.costPerResult):null],["Resultados",comparable?pct(d.currentMetrics.results,d.previousMetrics.results):null]];return changes.filter(([,c])=>c!==null&&Math.abs(c)>=30).map(([metric,c])=>({entityId:d.entityId,entityName:d.entityName,severity:Math.abs(c!)>=60?"critical":"warning",metric,changePercent:Math.round(c!*10)/10,message:`${metric} cambió ${c!>0?"+":""}${c!.toFixed(1)}% frente al periodo anterior.`}));});
 if(goals.targetCostPerResult&&goals.targetCostPerResult>0)for(const d of decisions){if(d.currentResultsAvailable===false||d.currentMetrics.results<=0)continue;const v=((d.currentMetrics.costPerResult-goals.targetCostPerResult)/goals.targetCostPerResult)*100;if(Math.abs(v)>=20)anomalies.push({entityId:d.entityId,entityName:d.entityName,severity:v>40?"critical":"warning",metric:"Costo por resultado vs objetivo",changePercent:Math.round(v*10)/10,message:`El costo por resultado está ${Math.abs(v).toFixed(1)}% ${v>0?"por encima":"por debajo"} del objetivo configurado.`});}
 const budgetRecommendations=portfolioRecommendations.map(item=>({fromEntityId:item.fromCampaignId,fromEntityName:item.fromCampaignName,toEntityId:item.toCampaignId,toEntityName:item.toCampaignName,suggestedPercent:item.action==="TEST_REALLOCATION"?10:0,confidence:"medium" as const,rationale:item.nextStep}));
 const creativeInsights=decisions.filter(d=>d.entityType==="ad").map(d=>({adId:d.entityId,adName:d.entityName,status:d.action==="REFRESH_CREATIVE"?"needs_refresh" as const:d.action==="SCALE"?"winner" as const:d.action==="MAINTAIN"?"healthy" as const:"observe" as const,score:d.score,message:d.rationale})).sort((a,b)=>b.score-a.score);
 const experiments=decisions.filter(d=>!blocked.has(d.entityId)&&["REFRESH_CREATIVE","REVIEW_AUDIENCE"].includes(d.action)).filter((d,i,all)=>all.findIndex(item=>item.campaignId===d.campaignId)===i).slice(0,3).map(d=>({id:`exp:${d.entityId}:${d.action}`,entityId:d.entityId,entityName:d.entityName,hypothesis:d.action==="REFRESH_CREATIVE"?"Una nueva variante creativa puede recuperar CTR sin cambiar audiencia ni presupuesto.":"Una audiencia alternativa puede mejorar eficiencia manteniendo creativo y presupuesto.",variable:d.action==="REFRESH_CREATIVE"?"creative" as const:"audience" as const,guardrail:"Cambiar una sola variable y no declarar ganador con evidencia insuficiente.",successMetric:["LEAD_GENERATION","MESSAGES","CONVERSIONS","SALES"].includes(d.objective)?"Costo por resultado y volumen de resultados":d.objective==="TRAFFIC"?"CTR y CPC":"Reach y CPM"}));
 // A projected result needs a future horizon and daily time series. Multiplying
 // two completed-period totals would only manufacture a forecast.
 const forecast={basis:"insufficient_data" as const,projectedResults:null,projectedSpend:null,uncertaintyPercent:100,warning:"Proyección no disponible: hace falta una serie diaria y un horizonte futuro definido."};
 const uniqueCampaigns=(items:PerformanceDecision[])=>items.filter((d,i,all)=>all.findIndex(item=>item.campaignId===d.campaignId)===i);
 const urgent=uniqueCampaigns(decisions.filter(d=>["PAUSE_CANDIDATE","REDUCE","REFRESH_CREATIVE","REVIEW_AUDIENCE"].includes(d.action)&&d.confidence!=="low")),healthy=uniqueCampaigns(decisions.filter(d=>["SCALE","MAINTAIN"].includes(d.action)&&d.confidence!=="low"));const brief={headline:urgent.length?`${urgent.length} campaña(s) requieren atención; ${healthy.length} muestran señales saludables.`:portfolioRecommendations.length?`${portfolioRecommendations.length} comparación(es) de presupuesto merecen revisión; confirma la calidad antes de mover inversión.`:`Sin cambios urgentes basados en los datos disponibles; ${healthy.length} campaña(s) muestran señales saludables.`,attention:[...urgent.slice(0,4).map(d=>`${d.entityName}: ${d.rationale}`),...portfolioRecommendations.slice(0,1).map(item=>item.nextStep)],healthy:healthy.slice(0,4).map(d=>`${d.entityName}: ${d.rationale}`)};
 return{generatedAt:new Date().toISOString(),goals,decisions,anomalies,budgetRecommendations,creativeInsights,experiments,learningGuards,forecast,brief,executionMode:"recommend_only",limitations:["ANLUX no modifica campañas ni presupuestos de Meta; las acciones son simulaciones/recomendaciones.","La memoria histórica depende de la configuración y de la disponibilidad de Supabase; las comparaciones del motor usan los periodos disponibles de Meta.","ROAS requiere valor de conversión fiable; no se inventa cuando Meta no lo proporciona."]};
}
